### ISSUE TITLE
IP address in NoMLBB

### ISSUE THREAD

**Issue by joe820912boy** [MDP43140/BaDomain#2]
It seems that some ip address block in NoMLBB.txt is incorrect?

224.0.0.0 is reserved for multicast used and 
192.168.0.0 maybe for local host?

Ref: [Reserved_IP_addresses](https://en.wikipedia.org/wiki/Reserved_IP_addresses)

**Comment by MDP43140** [comment]
Oh yeah, i realized that these lists of IP addresses in NoMLBB.txt aren't linking to Moonton servers in any way, its IANA reserved IP addreses:
`169.254.0.0
172.16.0.0
192.0.0.0
192.0.2.0
192.168.0.0
198.18.0.0
198.51.100.0
203.0.113.0
224.0.0.0`.

I will remove them soon as they don't link to any moonton servers in any way. by the way, i got those IP addresses from copy-pasting from another source, hence why that might be the case?

**Comment by joe820912boy** [comment]
Maybe the source exists some fp in list?
Should check the source has fix this error
